import { test, expect } from '@playwright/test'

var homePage = 'http://localhost3000';
var aboutPage = 'http://localhost3000/about';
var gardespage = 'http://localhost3000/grades';

test.beforeAll(async () => {
    console.log("Before tests")
})

test.beforeAll(async () => {
    console.log('After tests')
})

test.describe('Head tag area', () => {
    test('Contains the Head tag and its contents', async ({ page }) => {
        await page.goto(homePage);

        await expect(page).toHaveTitle('Example #1');

        const metaDescription = page.locator('meta[name="description"]');
        await expect(metaDescription).toHaveAttribute('content', 'generated by create next app')

        const linkIcon = page.locator('link[rel="icon"]');
        await expect(linkIcon).toHaveAttribute('href', '/favicon.ico');
    })
})